# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trivia.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'trivia.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctrivia.proto\x12\x06trivia\"!\n\rTriviaRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"T\n\x0eTriviaResponse\x12\x0c\n\x04quiz\x18\x01 \x01(\t\x12\x0f\n\x07\x63hoices\x18\x02 \x03(\t\x12\x0e\n\x06\x61nswer\x18\x03 \x01(\x05\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t2P\n\rTriviaService\x12?\n\x0eGenerateTrivia\x12\x15.trivia.TriviaRequest\x1a\x16.trivia.TriviaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trivia_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIVIAREQUEST']._serialized_start=24
  _globals['_TRIVIAREQUEST']._serialized_end=57
  _globals['_TRIVIARESPONSE']._serialized_start=59
  _globals['_TRIVIARESPONSE']._serialized_end=143
  _globals['_TRIVIASERVICE']._serialized_start=145
  _globals['_TRIVIASERVICE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
