# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import trivia_pb2 as proto_dot_trivia__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/trivia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TriviaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateTrivia = channel.unary_unary(
                '/trivia.TriviaService/GenerateTrivia',
                request_serializer=proto_dot_trivia__pb2.TriviaRequest.SerializeToString,
                response_deserializer=proto_dot_trivia__pb2.TriviaResponse.FromString,
                _registered_method=True)


class TriviaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateTrivia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TriviaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateTrivia': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTrivia,
                    request_deserializer=proto_dot_trivia__pb2.TriviaRequest.FromString,
                    response_serializer=proto_dot_trivia__pb2.TriviaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trivia.TriviaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trivia.TriviaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TriviaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateTrivia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trivia.TriviaService/GenerateTrivia',
            proto_dot_trivia__pb2.TriviaRequest.SerializeToString,
            proto_dot_trivia__pb2.TriviaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
